#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e3a7348b9567d6ca89205823e8e201faa918307d.name = "Upgrade from 2026.07.11~ynh1 (with Trixie deps fix)"
