#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d2579fe7b92f353e4ec18c3b4597a8c766300315.name = "Upgrade from 2023.08.08~ynh1 (packaging v2 and no full_domain)"
